Repository PatelN123/Digital-Support-Notes, pull requests merged in 2022-01, with the labels that each got.

#26 Add legislation pages
  docs/Legislation/British Computer Society.mdx
  docs/Legislation/Chartered Institute of Information Security.mdx
  docs/Legislation/Code of Conduct.mdx
  docs/Legislation/Institution of Analysts and Programmers.mdx
  docs/Legislation/Keeping up to date.mdx
Labels: enhancement

#27 Add `Data Analysis` category and a page.
  docs/Data Analysis/Techniques.mdx
  docs/Data Analysis/_category_.yml
Labels: enhancement

#36 Add Fault analysis category with all pages.
  docs/Diversity and Inclusion/Lawful Discrimination.mdx
  docs/Fault Analysis/ITIL.mdx
  docs/Fault Analysis/Incident Catrgorisation.mdx
  docs/Fault Analysis/Incident Logging.mdx
  docs/Fault Analysis/Incident Response.mdx
  docs/Fault Analysis/Incident&Problem.mdx
  docs/Fault Analysis/IncidentPrioritisation.mdx
  docs/Fault Analysis/IncidentStatuses.mdx
  docs/Fault Analysis/Priority Categories.mdx
  docs/Fault Analysis/Root Cause Analysis.mdx/5 whys.mdx
  docs/Fault Analysis/Root Cause Analysis.mdx/About.mdx
  docs/Fault Analysis/Root Cause Analysis.mdx/ETA.mdx
  docs/Fault Analysis/Root Cause Analysis.mdx/FMEA.mdx
  docs/Fault Analysis/Root Cause Analysis.mdx/Fishbone.mdx
  docs/Fault Analysis/Root Cause Analysis.mdx/Pareto Charts.mdx
  docs/Fault Analysis/Root Cause Analysis.mdx/Scatter Plots.mdx
  docs/Fault Analysis/Root Cause Analysis.mdx/_category_.yml
  docs/Fault Analysis/Technicians Levels/Level 1.mdx
  docs/Fault Analysis/Technicians Levels/Level 2.mdx
  docs/Fault Analysis/Technicians Levels/Level 3.mdx
  docs/Fault Analysis/Technicians Levels/_category_.yml
  docs/Fault Analysis/_category_.yml
  docs/Fault Analysis/info.mdx
  static/img/5whys.png
  static/img/fishbone.png
  static/img/fmea.png
  static/img/pareto.png
Labels: documentation, enhancement

#35 Create copyright.mdx
  docs/Legislation/copyright.mdx
Labels: documentation, enhancement

#91 Computer Science Revision notes
  Website/docs/computerscience/Processor Characteristics/Structure & Function of Processor.mdx
  Website/docs/computerscience/Processor Characteristics/_category_.yml
Labels: documentation, enhancement

#108 Computer science section 1 - to be completed
  Website/docs/computerscience/Section One/CPU and System Performance.mdx
  Website/docs/computerscience/Section One/Components of a Computer System.mdx
  Website/docs/computerscience/Section One/Secondary Storage.mdx
  Website/docs/computerscience/Section One/The CPU.mdx
  Website/docs/computerscience/Section One/The OS.mdx
  Website/docs/computerscience/Section One/Utility Software.mdx
  Website/docs/computerscience/Section One/_category_.yml
Labels: documentation, enhancement, claimed
